# Configuration for Revive linter (https://github.com/mgechev/revive)

ignoreGeneratedHeader = false
confidence = 0.8
severity = "warning"
warningCode = 0
errorCode = 0

[rule.argument-limit]
arguments = [4]
[rule.blank-imports]
[rule.confusing-naming]
[rule.confusing-results]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.errorf]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.struct-tag]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.var-declaration]
[rule.var-naming]
